# Generated by Django 4.0.8 on 2022-11-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_premium_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='premium_expire',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Действует до'),
        ),
    ]
