# Generated by Django 4.1.3 on 2023-01-19 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    replaces = [
        ("core", "0001_initial"),
        ("core", "0002_alter_order_provider_payment_charge_id_and_more"),
        ("core", "0003_ticket"),
        ("core", "0004_alter_ticket_options"),
        ("core", "0005_parserentry"),
        ("core", "0006_targets_alter_parserentry_source"),
        ("core", "0007_rename_targets_target"),
        ("core", "0008_parserentry_pid"),
        ("core", "0009_alter_order_status"),
        ("core", "0010_target_daily_price"),
        ("core", "0011_rename_target_service_alter_service_options"),
        ("core", "0012_ticket_reply_alter_ticket_message"),
        ("core", "0013_delete_ticket"),
        ("core", "0014_delete_parserentry"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FAILURE", "Failure"),
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                        ],
                        default="PENDING",
                        max_length=55,
                    ),
                ),
                ("invoice_payload", models.CharField(max_length=55)),
                ("currency", models.CharField(max_length=5)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=11)),
                (
                    "telegram_payment_charge_id",
                    models.CharField(editable=False, max_length=100),
                ),
                (
                    "provider_payment_charge_id",
                    models.CharField(editable=False, max_length=100),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("title", models.CharField(max_length=55, verbose_name="Title")),
                ("url_body", models.URLField(max_length=100, verbose_name="URL body")),
                (
                    "url_query",
                    models.URLField(
                        blank=True, max_length=100, verbose_name="URL query"
                    ),
                ),
                (
                    "daily_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Daily Price",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
    ]
