# Generated by Django 4.0.8 on 2022-11-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_ticket"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"verbose_name": "Ticket", "verbose_name_plural": "Tickets"},
        ),
    ]
