# Generated by Django 4.0.8 on 2022-11-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_targets_alter_parserentry_source"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Targets",
            new_name="Target",
        ),
    ]
