# Generated by Django 4.0.8 on 2022-11-13 12:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_targets_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserentry',
            name='pid',
            field=models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=100, verbose_name='Project ID'),
        ),
    ]
