# Generated by Django 4.0.8 on 2022-11-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_rename_target_service_alter_service_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="reply",
            field=models.TextField(blank=True, verbose_name="Ответ"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="message",
            field=models.TextField(verbose_name="Вопрос"),
        ),
    ]
