# Generated by Django 4.1.3 on 2023-01-19 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_ticket_reply_alter_ticket_message"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ticket",
        ),
    ]
