# Generated by Django 4.1.3 on 2023-01-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_delete_ticket"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ParserEntry",
        ),
    ]
