# Generated by Django 4.0.8 on 2022-11-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='premium_expire',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='Действует до'),
        ),
    ]
