# Generated by Django 4.0.8 on 2022-11-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
