# Generated by Django 4.0.8 on 2022-11-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_created_remove_user_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='premium_expire',
            field=models.DateTimeField(blank=True, default=''),
        ),
    ]
