# Generated by Django 4.0.8 on 2022-11-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_premium_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='premium_expire',
            field=models.DateTimeField(blank=True, default='', verbose_name='Действует до'),
        ),
        migrations.AlterField(
            model_name='user',
            name='premium_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('regular', 'Regular'), ('permanent', 'Permanent'), ('expired', 'Expired')], default='expired', max_length=55, verbose_name='Статус'),
        ),
    ]
