# Generated by Django 4.0.8 on 2022-11-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_target_service_alter_service_options'),
        ('users', '0004_remove_user_services_user_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(blank=True, to='core.service'),
        ),
    ]
