# Generated by Django 4.0.8 on 2022-11-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_premium_expire_alter_user_premium_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
