# Generated by Django 4.0.8 on 2022-11-13 09:13

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_parserentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=55, verbose_name='Title')),
                ('url_body', models.URLField(max_length=100, verbose_name='URL body')),
                ('url_query', models.URLField(blank=True, max_length=100, verbose_name='URL query')),
            ],
            options={
                'verbose_name': 'Target',
                'verbose_name_plural': 'Targets',
            },
        ),
        migrations.AlterField(
            model_name='parserentry',
            name='source',
            field=models.CharField(max_length=55, verbose_name='Source'),
        ),
    ]
