# Generated by Django 4.0.8 on 2022-11-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_parserentry_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('FAILURE', 'Failure'), ('PENDING', 'Pending'), ('SUCCESS', 'Success')], default='PENDING', max_length=55),
        ),
    ]
