# Generated by Django 4.0.8 on 2022-11-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Daily Price'),
        ),
    ]
